InputDispatcher: fix code for clang update
After clang update, we got below errors:

frameworks/native/services/inputflinger/dispatcher/InputDispatcher.cpp:5882:27:
error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
    auto command = [this, application = std::move(application)]() REQUIRES(mLock) {
                          ^
frameworks/native/services/inputflinger/dispatcher/InputDispatcher.cpp:5877:75:
note: previous declaration is here
void InputDispatcher::onAnrLocked(std::shared_ptr<InputApplicationHandle> application) {
                                                                          ^
frameworks/native/services/inputflinger/dispatcher/InputDispatcher.cpp:5945:39:
error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
    auto command = [this, token, pid, reason = std::move(reason)]() REQUIRES(mLock) {
                                      ^
frameworks/native/services/inputflinger/dispatcher/InputDispatcher.cpp:5944:71:
note: previous declaration is here
                                                          std::string reason) {
                                                                      ^

Bug: 280683256
Test: build with clang-r498229
Change-Id: I478067e4dff9e6d512e84ca5a9f394d4defb89ee